<?php

return [
    'admin' => [
        ['type' => 'header', 'label' => 'MAIN'],
        [
            'label' => 'Dashboard',
            'icon' => 'zmdi-home',
            'route' => 'dashboard',
            'active' => 'dashboard',
        ],
        [
            'label' => 'Appointment',
            'icon' => 'zmdi-calendar-check',
            'route' => 'appointments.create',
            'active' => 'appointments.*',
        ],
        [
            'label' => 'Doctors',
            'icon' => 'zmdi-account-add',
            'active' => 'doctors.*|pages.profile|pages.events',
            'children' => [
                ['label' => 'All Doctors', 'route' => 'doctors.index', 'active' => 'doctors.index'],
                ['label' => 'Add Doctor', 'route' => 'doctors.create', 'active' => 'doctors.create'],
                ['label' => 'Doctor Profile', 'route' => 'pages.profile', 'active' => 'pages.profile'],
                ['label' => 'Doctor Schedule', 'route' => 'pages.events', 'active' => 'pages.events'],
            ],
        ],
        [
            'label' => 'Patients',
            'icon' => 'zmdi-account-o',
            'active' => 'patients.*|pages.patient-profile|pages.patient-invoice',
            'children' => [
                ['label' => 'All Patients', 'route' => 'patients.index', 'active' => 'patients.index'],
                ['label' => 'Add Patient', 'route' => 'patients.create', 'active' => 'patients.create'],
                ['label' => 'Patient Profile', 'route' => 'pages.patient-profile', 'active' => 'pages.patient-profile'],
                ['label' => 'Invoice', 'route' => 'pages.patient-invoice', 'active' => 'pages.patient-invoice'],
            ],
        ],
        [
            'label' => 'Payments',
            'icon' => 'zmdi-balance-wallet',
            'active' => 'pages.payments|pages.add-payments|pages.invoice',
            'children' => [
                ['label' => 'Payments', 'route' => 'pages.payments', 'active' => 'pages.payments'],
                ['label' => 'Add Payment', 'route' => 'pages.add-payments', 'active' => 'pages.add-payments'],
                ['label' => 'Invoice', 'route' => 'pages.invoice', 'active' => 'pages.invoice'],
            ],
        ],
        [
            'label' => 'Departments',
            'icon' => 'zmdi-label-alt',
            'active' => 'departments.*|pages.more-departments',
            'children' => [
                ['label' => 'Add', 'route' => 'departments.create', 'active' => 'departments.create'],
                ['label' => 'All Departments', 'route' => 'departments.index', 'active' => 'departments.index'],
                ['label' => 'Cardiology', 'url' => 'javascript:void(0);'],
                ['label' => 'Pulmonology', 'url' => 'javascript:void(0);'],
                ['label' => 'Gynecology', 'url' => 'javascript:void(0);'],
                ['label' => 'Neurology', 'url' => 'javascript:void(0);'],
                ['label' => 'Urology', 'url' => 'javascript:void(0);'],
                ['label' => 'Gastrology', 'url' => 'javascript:void(0);'],
                ['label' => 'Pediatrician', 'url' => 'javascript:void(0);'],
                ['label' => 'Laboratory', 'url' => 'javascript:void(0);'],
            ],
        ],
        [
            'label' => 'System Settings',
            'icon' => 'zmdi-settings',
            'route' => 'settings.index',
            'active' => 'settings.*',
        ],
        [
            'label' => 'Authentication',
            'icon' => 'zmdi-lock',
            'active' => 'login|pages.sign-up|pages.forgot-password|pages.404|pages.500|pages.page-offline|pages.locked',
            'children' => [
                ['label' => 'Sign In', 'route' => 'login', 'active' => 'login'],
                ['label' => 'Sign Up', 'route' => 'pages.sign-up', 'active' => 'pages.sign-up'],
                ['label' => 'Forgot Password', 'route' => 'pages.forgot-password', 'active' => 'pages.forgot-password'],
                ['label' => 'Page 404', 'route' => 'pages.404', 'active' => 'pages.404'],
                ['label' => 'Page 500', 'route' => 'pages.500', 'active' => 'pages.500'],
                ['label' => 'Page Offline', 'route' => 'pages.page-offline', 'active' => 'pages.page-offline'],
                ['label' => 'Locked Screen', 'route' => 'pages.locked', 'active' => 'pages.locked'],
            ],
        ],
        ['type' => 'header', 'label' => 'EXTRA COMPONENTS'],
        [
            'label' => 'Blog',
            'icon' => 'zmdi-blogger',
            'active' => 'pages.blog-*',
            'children' => [
                ['label' => 'Blog Dashboard', 'route' => 'pages.blog-dashboard', 'active' => 'pages.blog-dashboard'],
                ['label' => 'New Post', 'route' => 'pages.blog-post', 'active' => 'pages.blog-post'],
                ['label' => 'Blog List', 'route' => 'pages.blog-list', 'active' => 'pages.blog-list'],
                ['label' => 'Blog Grid', 'route' => 'pages.blog-grid', 'active' => 'pages.blog-grid'],
                ['label' => 'Blog Single', 'route' => 'pages.blog-details', 'active' => 'pages.blog-details'],
            ],
        ],
        [
            'label' => 'File Manager',
            'icon' => 'zmdi-folder',
            'active' => 'pages.file-*',
            'children' => [
                ['label' => 'All File', 'route' => 'pages.file-dashboard', 'active' => 'pages.file-dashboard'],
                ['label' => 'Documents', 'route' => 'pages.file-documents', 'active' => 'pages.file-documents'],
                ['label' => 'Media', 'route' => 'pages.file-media', 'active' => 'pages.file-media'],
                ['label' => 'Images', 'route' => 'pages.file-images', 'active' => 'pages.file-images'],
            ],
        ],
        [
            'label' => 'App',
            'icon' => 'zmdi-apps',
            'active' => 'pages.mail-*|pages.chat|pages.contact',
            'children' => [
                ['label' => 'Inbox', 'route' => 'pages.mail-inbox', 'active' => 'pages.mail-inbox'],
                ['label' => 'Chat', 'route' => 'pages.chat', 'active' => 'pages.chat'],
                ['label' => 'Contact list', 'route' => 'pages.contact', 'active' => 'pages.contact'],
            ],
        ],
        [
            'label' => 'Widgets',
            'icon' => 'zmdi-delicious',
            'active' => 'pages.widgets-*',
            'children' => [
                ['label' => 'Apps Widgetse', 'route' => 'pages.widgets-app', 'active' => 'pages.widgets-app'],
                ['label' => 'Data Widgetse', 'route' => 'pages.widgets-data', 'active' => 'pages.widgets-data'],
            ],
        ],
        [
            'label' => 'Sample Pages',
            'icon' => 'zmdi-copy',
            'active' => 'pages.blank|pages.dashboard-rtl|pages.image-gallery|pages.profile|pages.timeline|pages.invoice|pages.search-results',
            'children' => [
                ['label' => 'Blank Page', 'route' => 'pages.blank', 'active' => 'pages.blank'],
                ['label' => 'RTL Support', 'route' => 'pages.dashboard-rtl', 'active' => 'pages.dashboard-rtl'],
                ['label' => 'Image Gallery', 'route' => 'pages.image-gallery', 'active' => 'pages.image-gallery'],
                ['label' => 'Profile', 'route' => 'pages.profile', 'active' => 'pages.profile'],
                ['label' => 'Timeline', 'route' => 'pages.timeline', 'active' => 'pages.timeline'],
                ['label' => 'Invoices', 'route' => 'pages.invoice', 'active' => 'pages.invoice'],
                ['label' => 'Search Results', 'route' => 'pages.search-results', 'active' => 'pages.search-results'],
            ],
        ],
        [
            'label' => 'User Interface (UI)',
            'icon' => 'zmdi-swap-alt',
            'active' => 'pages.ui-kit|pages.alerts|pages.collapse|pages.colors|pages.dialogs|pages.icons|pages.list-group|pages.media-object|pages.modals|pages.notifications|pages.progressbars|pages.range-sliders|pages.sortable-nestable|pages.tabs|pages.waves',
            'children' => [
                ['label' => 'UI KIT', 'route' => 'pages.ui-kit', 'active' => 'pages.ui-kit'],
                ['label' => 'Alerts', 'route' => 'pages.alerts', 'active' => 'pages.alerts'],
                ['label' => 'Collapse', 'route' => 'pages.collapse', 'active' => 'pages.collapse'],
                ['label' => 'Colors', 'route' => 'pages.colors', 'active' => 'pages.colors'],
                ['label' => 'Dialogs', 'route' => 'pages.dialogs', 'active' => 'pages.dialogs'],
                ['label' => 'Icons', 'route' => 'pages.icons', 'active' => 'pages.icons'],
                ['label' => 'List Group', 'route' => 'pages.list-group', 'active' => 'pages.list-group'],
                ['label' => 'Media Object', 'route' => 'pages.media-object', 'active' => 'pages.media-object'],
                ['label' => 'Modals', 'route' => 'pages.modals', 'active' => 'pages.modals'],
                ['label' => 'Notifications', 'route' => 'pages.notifications', 'active' => 'pages.notifications'],
                ['label' => 'Progress Bars', 'route' => 'pages.progressbars', 'active' => 'pages.progressbars'],
                ['label' => 'Range Sliders', 'route' => 'pages.range-sliders', 'active' => 'pages.range-sliders'],
                ['label' => 'Sortable & Nestable', 'route' => 'pages.sortable-nestable', 'active' => 'pages.sortable-nestable'],
                ['label' => 'Tabs', 'route' => 'pages.tabs', 'active' => 'pages.tabs'],
                ['label' => 'Waves', 'route' => 'pages.waves', 'active' => 'pages.waves'],
            ],
        ],
        ['type' => 'header', 'label' => 'Extra'],
        ['type' => 'widgets'],
    ],

    'doctor' => [
        [
            'label' => 'Dashboard',
            'icon' => 'zmdi-home',
            'route' => 'dashboard',
            'active' => 'dashboard',
        ],
        [
            'label' => 'My Patients',
            'icon' => 'zmdi-account-o',
            'active' => 'patients.*',
            'children' => [
                ['label' => 'All Patients', 'route' => 'patients.index', 'active' => 'patients.index'],
                ['label' => 'Add Patient', 'route' => 'patients.create', 'active' => 'patients.create'],
            ],
        ],
    ],
];
