<?php

return [
    'brand_name' => 'Lineup Aligner',

    'defaults' => [
        'project_name' => 'Lineup Aligner',
        'logo' => '',
        'clinic_name' => 'Lineup Aligner',
        'clinic_email' => '',
        'clinic_phone' => '',
        'clinic_address' => '',
        'system_timezone' => 'UTC',
        'scan_requirement' => 'optional',
        'notifications_enabled' => '1',
        'notification_email_enabled' => '1',
        'notification_sound_enabled' => '1',
        'notification_types' => '',
        'theme_skin' => 'cyan',
        'brand_primary' => '',
        'brand_secondary' => '#09243c',
        'dashboard_font' => 'cairo',
        'dashboard_color_mode' => 'light',
        'left_menu_style' => 'light',
    ],

    'scan_requirements' => [
        'optional' => 'Optional — upper, lower, or both',
        'at_least_one' => 'At least one jaw scan required',
        'both' => 'Both upper and lower scans required',
    ],

    'timezones' => [
        'UTC' => 'UTC',
        'America/New_York' => 'Eastern Time (US & Canada)',
        'America/Chicago' => 'Central Time (US & Canada)',
        'America/Denver' => 'Mountain Time (US & Canada)',
        'America/Los_Angeles' => 'Pacific Time (US & Canada)',
        'America/Toronto' => 'Toronto',
        'Europe/London' => 'London',
        'Europe/Paris' => 'Paris / Central Europe',
        'Europe/Berlin' => 'Berlin',
        'Asia/Dubai' => 'Dubai',
        'Asia/Riyadh' => 'Riyadh',
        'Asia/Amman' => 'Amman',
        'Asia/Kolkata' => 'India',
        'Asia/Singapore' => 'Singapore',
        'Australia/Sydney' => 'Sydney',
    ],

    'fonts' => [
        'cairo' => [
            'label' => 'Cairo',
            'family' => 'Cairo',
            'stack' => "'Cairo', -apple-system, BlinkMacSystemFont, 'Segoe UI', Tahoma, sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700&display=swap',
        ],
        'inter' => [
            'label' => 'Inter',
            'family' => 'Inter',
            'stack' => "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
        ],
        'roboto' => [
            'label' => 'Roboto',
            'family' => 'Roboto',
            'stack' => "'Roboto', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap',
        ],
        'open-sans' => [
            'label' => 'Open Sans',
            'family' => 'Open Sans',
            'stack' => "'Open Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap',
        ],
        'poppins' => [
            'label' => 'Poppins',
            'family' => 'Poppins',
            'stack' => "'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap',
        ],
        'nunito-sans' => [
            'label' => 'Nunito Sans',
            'family' => 'Nunito Sans',
            'stack' => "'Nunito Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;500;600;700&display=swap',
        ],
        'lato' => [
            'label' => 'Lato',
            'family' => 'Lato',
            'stack' => "'Lato', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap',
        ],
        'tajawal' => [
            'label' => 'Tajawal',
            'family' => 'Tajawal',
            'stack' => "'Tajawal', -apple-system, BlinkMacSystemFont, 'Segoe UI', Tahoma, sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700&display=swap',
        ],
        'dm-sans' => [
            'label' => 'DM Sans',
            'family' => 'DM Sans',
            'stack' => "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap',
        ],
        'plus-jakarta-sans' => [
            'label' => 'Plus Jakarta Sans',
            'family' => 'Plus Jakarta Sans',
            'stack' => "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
            'google_url' => 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap',
        ],
    ],

    'skins' => [
        'purple' => ['label' => 'Purple', 'color' => '#6572b8'],
        'blue' => ['label' => 'Blue', 'color' => '#60bafd'],
        'cyan' => ['label' => 'Cyan', 'color' => '#00cfd1'],
        'teal' => ['label' => 'Teal', 'color' => '#26a69a'],
        'green' => ['label' => 'Green', 'color' => '#50d38a'],
        'lime' => ['label' => 'Lime', 'color' => '#c0ca33'],
        'orange' => ['label' => 'Orange', 'color' => '#ffc323'],
        'amber' => ['label' => 'Amber', 'color' => '#ffb300'],
        'blush' => ['label' => 'Blush', 'color' => '#ff758e'],
        'pink' => ['label' => 'Pink', 'color' => '#ec407a'],
        'coral' => ['label' => 'Coral', 'color' => '#ff8a65'],
        'red' => ['label' => 'Red', 'color' => '#ef5350'],
        'indigo' => ['label' => 'Indigo', 'color' => '#5c6bc0'],
        'deep-purple' => ['label' => 'Deep Purple', 'color' => '#7e57c2'],
        'brown' => ['label' => 'Brown', 'color' => '#8d6e63'],
        'slate' => ['label' => 'Slate', 'color' => '#546e7a'],
    ],
];
